name: vivictpp # you probably want to 'snapcraft register <name>'
license: GPL-3.0
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Vivict video comparison tool++
description: |
  Side-by-side/split-view video comparison tool. See also https://github.com/svt/vivictpp

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  vivictpp:
    command: usr/local/bin/vivictpp.wrapper
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
    plugs:
      - audio-playback
      - alsa
      - pulseaudio
      - network
      - x11
  ffmpeg:
    command: usr/bin/ffmpeg

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/alsa/conf.d:
    bind: $SNAP/etc/alsa/conf.d
    
parts:
  scripts:
    source: scripts/
    plugin: dump
    organize:
      vivictpp.wrapper : usr/local/bin/vivictpp.wrapper
  
  vivictpp:
    build-packages:
      - pkg-config
      - cmake
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libavformat-dev
      - libavcodec-dev
      - libavutil-dev
      - libfreetype6-dev
      - libswscale-dev
      - libavfilter-dev
      - git
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-ttf-2.0-0
      - ffmpeg
      - libfreetype6
      - libglu1-mesa
      - freeglut3
      - libpulse0
    # See 'snapcraft plugins'
    source: /root/project
    source-type: local
    plugin: meson
