name: macos-build
on: push
jobs:
  macos-build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ffmpeg and ssl
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        run: |
          brew update
          brew install --overwrite python@3.11
          brew install --overwrite meson ninja cmake sdl2 sdl2_ttf ffmpeg@4
      - name: Meson build
        env:
          PKG_CONFIG_PATH: "/usr/local/opt/ffmpeg@4/lib/pkgconfig"
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
      - name: Save logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: macos-build-logs
          path: build/meson-logs
